# .streamlit/secrets.toml

[supabase]
url = "https://dgidkofqqxcsjegeggox.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnaWRrb2ZxcXhjc2plZ2VnZ294Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyNTYyODEsImV4cCI6MjA4NjgzMjI4MX0.IfjHkPloBTzsVcSeaFo26sNGGofvpzRNfbVkpW9i86s"